### ISSUE TITLE
A few questions about the bi-weekly meeting

### ISSUE THREAD

**Issue by hev** [OpenObservability/OpenMetrics#106]
I work with a team at Pivotal focused on observability tools and am curious about the bi-weekly meeting. 

* Are they happening? The meeting notes from October are helpful. Are others just missing, or has the group not been actively meeting?
* How do I join? I joined the mailing list but wasn't clear how to join the meetings or when they occur
* Is there a process for proposing agenda items?

**Comment by SuperQ** [comment]
We have a meeting agenda / notes google doc, and calendar invite. We don't have an official process for joining yet.

**Comment by ahevenor** [comment]
I am most interested in how the team is defining a charter that is distinct from Prometheus and the instrumentation SIG.

**Comment by jkschneider** [comment]
Frankly, the composition of the contributors doesn't seem to represent the wide variety of concerns from monitoring systems that are substantively different from Prometheus/Stackdriver. I'd expect there to be representatives from companies like New Relic, Datadog, SignalFx, etc. if this is to truly be an open standard.

Otherwise, appearances are that this is just placing an "open" stamp on Prometheus' opinions.

**Comment by RichiH** [comment]
Prometheus is the starting point of this standard, mainly because this is where the effort started and also because of its incredibly wide adoption. As per the IETF, adoption and working code are the most important aspects of any standardization effort.

Given our repeated calls for participation within CNCF, the self-selected entities already actively working on this are the ones showing the most interest, by definition.

In the current phase, onboarding new people is probably counterproductive, but we would love to see wider discussion.

As an aside, Ilan Rabinovitch of Datadog seems pretty happy according to their quote on the CNCF annoucement.
