### ISSUE TITLE
Clarify what metrics are vs. event logging and other systems

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#22]
Even in our own discussions we're getting confused about what is and is not in scope for a metrics-based transport format. I expect this to continue to be an issue (it still is within the Prometheus ecosystem, even after a few years of being quite clear about it).

I think we should have an opening section covering the idea that metrics are regular snapshots of state, not statsd style samples, profiling or other event loggingy stuff.

**Comment by RichiH** [comment]
Nitpick, this is not for the abstract, it's for a "Scope" section or similar. Else, agreed. Potentially along with a "you can turn events into metrics if you want" as I found that helpful to make people really get the difference.

**Comment by brian-brazil** [comment]
Agreed, and example would be good. Might also be a place to hint at cardinality.

**Comment by manolama** [comment]
How about something like this as a start?

A metric is a single structured measurement or snapshot of state associated with a timestamp and identifier. For example, a temperature sensor at the South Pole in Antartica may measure -82.8C at 12:00:00 on 23 June, 1982. The metric value would be ``-82.8`` of the type ``float`` with units ``celcius``, a Unix Epoch timestamp of ``393681600`` and an identifier comprising of ``metric = sensor.temperature, location=South Pole``. 

In Prometheus text syntax the format would be ``....``

A time series is a collection of two or more metrics sharing the same identifier with unique timestamps.

Metrics are differentiated from events (or log information) in that events are typically irregular or exceptional occurrences that may or may not be structured..

**Comment by brian-brazil** [comment]
> A metric is a single structured measurement or snapshot of state associated with a timestamp and identifier. 

That's a sample. A metric is one or more timeseries, depending on the type and labels. There's also inconsistency in Prometheus land around whether a metric is one labelset (a "MetricFamily") or all the metrics with the same name but differing labels.

**Comment by manolama** [comment]
> A metric is one or more timeseries, depending on the type and labels.

I think that's where folks will get really confused. You have the "metric" which is really just another label but the first-class label that EVERY measurement must have. Then that "metric" label is associated with another set of labels to create the identifier. 

Then you have the Metric which, as you noted, some folks consider to be the time series. E.g. "I want to graph this metric". I personally don't like that definition because it gets really confusing since we moved to labels or tags. It used to be that in RRD or Graphite you'd have a metric which was always a single time series, e.g. ``web01.sys.cpu.pct_busy``. But now you have the "metric" with an additional set of identifiers so some users think "oh a metric is just one time series" and query for "metric = sys.cpu.pct_busy" but may not realize there are 10s to 1000s of time series sharing that metric name.

I'd personally prefer the older metric = 1 sample = 1 identifier definition.

**Comment by brian-brazil** [comment]
I think that confusion has always been there, even before labels.

We (inconsistently) make the distinction of metrics vs. time series in Prometheus. Compound types such as histograms make that more complicated, as a single un-labelled metric can consist of multiple time series.

**Comment by manolama** [comment]
Lets settle on some solid definitions for this project :)

**Comment by brian-brazil** [comment]
In this project we've been fairly consistent about time series vs metrics I believe. This issue is about metrics vs event logs, which is largely a documentation/scope thing we'll need in the final document.

**Comment by robskillington** [comment]
One question I wanted to raise, most definitely on the same page we would like separation of logs and event like data from metrics (e.g. traces, exceptions, or other text based values).  

With respect to supporting individual samples however, I think there needs to be a distinction of if this is going to be supported or not.  

We support the following very similar types of metrics counters, gauges and histograms but also support "timers" which is similar in nature to statsd "timers".  They are tag based but still emit a per event sample (unlike counters, gauges and histograms which are snapshots) and require aggregation outside of the process.

We should call out whether the format would allow for limited support for this kind of data or whether it should be limited to "snapshot"-able types.  If so we should discuss what metric libraries that want to support both "snapshot"-able types alongside types like statsd "timers" should do.  Do they expose two exposition formats, etc?

**Comment by robskillington** [comment]
FWIW to give context, our stats reporting libraries emit into both Prometheus and our own native format.  The timers type can be flowed into Prometheus summary types or Histogram types (i.e. in process aggregation) but for our native format these values are pushed directly out of process:
https://github.com/uber-go/tally#structure
https://github.com/uber-go/tally/tree/master/prometheus#a-buffered-prometheus-reporter

**Comment by brian-brazil** [comment]
> With respect to supporting individual samples however, I think there needs to be a distinction of if this is going to be supported or not.

That's event logging, which would be out of scope for a metrics standard.

**Comment by robskillington** [comment]
I see, makes sense.  

Maybe it's also worth beginning an "Open Event Logging" exposition format, even if only to start the initiative and redirect those wanting to work on those efforts to that project?

**Comment by brian-brazil** [comment]
I think the question is are you talking about logging in general, or do you just want a statsd?

**Comment by robskillington** [comment]
Not talking about logging that you would come across in a normal conversation.  There's a difference between "structured" logging which when discussed generally usually means just giving fields instead of text, but usually still free form.  Then theres "event logging" which are events encoded in a format that match a very strict schema.  The second type can be optimally encoded, i.e. msgpack, and you can actually aggregate on because you understand the event type.

I think statsd timer values could fall into that second category.

I'm going to open up an issue in this repository however about support for Q-Digest, which is another type we'd like to support ourselves and if this spec supported would be helpful for standardization purposes.

**Comment by brian-brazil** [comment]
Both of those cases are event logging from the standpoint of OpenMetrics. The exact format/structure of what is being logged isn't relevant, it's that it's about individual events that matters.

Having a statsd-like thing is not in scope, but is something we may want to cover in some fashion as the ecosystem will ultimately need one of those.

**Comment by jeromefroe** [comment]
Influx provides a good summary of the difference between [regular and irregular time series](https://www.influxdata.com/blog/why-build-a-time-series-data-platform/). Perhaps it would be beneficial to include something similar in regards to the distinction between time series deriving from metrics and time series deriving from events? An example of how the latter can be transformed into the former, for instance by incrementing a counter every time an event occurs, may also be helpful. In this way, it may be possible to better elucidate the use of metrics versus logs. For example, while the contents of exceptions should be logged, one may also want to maintain a counter for the number of exceptions thrown, so that it is easier to visualize trends over time and correlate with other metrics.

**Comment by brian-brazil** [comment]
That's exactly the sort of thing this issue is proposing :)
