### ISSUE TITLE
[Proposal] Constrain label values to exclude leading/trailing whitespace

### ISSUE THREAD

**Issue by dhoard** [OpenObservability/OpenMetrics#248]
**Proposal**

Constrain label value to exclude leading/trailing whitespace

**Background**

While doing development with the Prometheus `client_java` library, a bug in my local code that resulted in label values with leading/trailing whitespace.

```
foo_write_errors{name=" system1",} 0.0
```

This is consistent with the spec.

~~~~ abnf
label = label-name EQ DQUOTE escaped-string DQUOTE
~~~~

But from a practical standpoint doesn't make sense to me.

By constraining label values to exclude leading/trailing whitespace, the original developer can detect the bug in the exporter/code they are developing. (I don't see a real-world scenario where someone would want/need leading/trailing whitespace in a label value.)

While I can create a PR for the specific library I use (Prometheus `client_java`) to constrain/check the label value, it would be non-conformant without a spec change, and thus most likely be rejected.

**Comment by brian-brazil** [comment]
This is something that we have previously discussed, and it doesn't make sense. Label values can validly contain whitespace, particularly when there's procedural generation going on, and to do otherwise would cause unexpected breakage for users. It'd also be a breaking change compared to the Prometheus text format.

We support full UTF-8 in labels, and that includes whitespace.

**Comment by SuperQ** [comment]
Agreed, label values are opaque UTF-8 to the spec.

**Comment by dhoard** [comment]
Thanks for the insight.
