### ISSUE TITLE
Staleness markers / implications of missing time series

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#37]
For TSDB supporting a concept of staleness, it should be possible to mark TS as stale/not there any more. 

`stale` or `removed` probably make sense.

**Comment by brian-brazil** [comment]
This is currently an implementation specific Prometheus, and as far as I know we're the only time series database that does it in this particular way. For this to make sense as part of a spec, we'd likely have to incorporate the Prometheus design into the spec which I think would be a bit much.

**Comment by RichiH** [comment]
Staleness maybe, but optionally marking a time series as removed is potentially useful to other implementations as well.

**Comment by manolama** [comment]
Could be a meta flag.

**Comment by brian-brazil** [comment]
This isn't metadata, it'd be a special value for a particular time series.

**Comment by pauldix** [comment]
This feels a bit odd to me. If values exist in a time range then that series should exist in the result set. If they don't then they wouldn't. This is more an implementation detail for the backend. For example, in our upcoming language, IFQL:
```
select(db:"foo").where(exp:{"_metric"=="_node_cpu"}).last()
```

Would return the last value of all time series for all time (that exist in the DB). Where this would return something more like Prometheus instant metrics:
```
select(db:"foo").where(exp:{"_metric"=="_node_cpu"}).range(start:-5m).last()
```

Stale seems like an odd concept without specifying what length of time stale implies. Having it fixed at 5m due to an underlying implementation optimization doesn't seem right.

**Comment by mattbostock** [comment]
I agree that it seems to odd to include this in the exposition format. I'd expect a metric to be interpreted as 'stale' or 'removed' by its omission.

Using a termination marker (#11) would help to make omissions unequivocal.

**Comment by brian-brazil** [comment]
> where missing time series information indicates "no change" 

The way to represent no change is to have the same data point again.

**Comment by RichiH** [comment]
Consensus: It needs to be there every single time.
