### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by mattbostock** [OpenObservability/OpenMetrics#44]
We should have a code of conduct.

It'd make sense to use the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (as [Prometheus does](https://github.com/prometheus/prometheus/blob/master/code-of-conduct.md)). If others agree, then we need a couple of volunteers to be listed as contacts.

**Comment by RichiH** [comment]
We will need one anyway, as we will join CNCF. Personally, I prefer the FOSDEM one; but any balanced one will do.

**Comment by pimvanpelt** [comment]
I don't feel too strongly about it, but considering we're targeting OpenMetrics as a part of CNCF, I think it makes most sense to share the CoC with them. If you're looking for volunteers, I can be a named contact (perhaps more so because I do not work directly on any of the systems implementing OpenMetrics). We should have two people at least for redundancy / coverage purposes.

Let me know if you accept, and I'll send a PR adding a CoC + the representatives here.

**Comment by RichiH** [comment]
I will ask the CNCF TOC about this today. I think it would be best if we had the contact people outside of the whole project; maybe CNCF can help us with that.

**Comment by caniszczyk** [comment]
If you're a CNCF project, we ask you default to this: https://github.com/cncf/foundation/blob/master/code-of-conduct.md

**Comment by RichiH** [comment]
@caniszczyk Just added this to the TOC slides: Can you help us with contact people? There's not a single female in OM, atm.

**Comment by caniszczyk** [comment]
@RichiH for now, I'd recommend you simply default to https://www.contributor-covenant.org/ until the project is officially part of CNCF
