### ISSUE TITLE
Annotations on top of labels?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#45]
Chris Larsen would like to have annotations; labels which don't change the identity of a series.

Similar to https://prometheus.io/docs/alerting/rules/ annotations.

**Comment by brian-brazil** [comment]
Can we expand on which type of annotations these are?

**Comment by RichiH** [comment]
Chris should expand on this, but I can think of stuff which would otherwise live in `_info`, or `ifDescr` et al.

**Comment by manolama** [comment]
There are a few types of annotations and use cases:

1) Tightly coupled decorations on a specific data point (or data points) for a specific time series. These can be embedded with the metric when sent over the wire or added later. Some examples of the former would Monarch's exemplars where you pick a sample trace ID to associate with a data point or if you restart a process, it may emit the version or restart cause with the first recording of the uptime metric. Also the idea of status messages, when a time series flips to an error value, it's useful to send and store an exception or state that's associated with that data point for debugging. An annotation added later would be team member typing in a note about some spike in a graph, literally annotating something, so that when other users view the same time range they'll see the note. 

The content of the annotation can be a simple string or something structured, that can be implementation specific, but it shares the same, fully qualified identifier (metric + labels) as the numeric time series. A query containing that time series can then scoop up the associated annotations and, typically, display them as callouts on a graph or list them in a side-bar, however UIs want to handle it.

Because these types of annotations are tightly coupled with a metric, I think it's worth having in the data spec. But I'd also want it to be a first level construct. Implementations can then decide how to flatten it, e.g. Prometheus would just take the data and create a new `_info` series I assume, and dump the details in a label. TSDB stores the string as is in the same row with the numeric data. Other systems typically shunt annotations into another store like ES, Solr or an RDBMS.

```
metric.foo 1483246800 42 host=web01, dc=phx
metric.foo 1483246800 "Joe Bob got the answer but not the question" host=web01, dc=phx
```

2) Another use case would be metric level annotations that would apply across all time series or sub-sets of the time series. E.g. code deployments, application-wide issues, data-center outages, etc. Since these aren't tightly coupled with a specific time series, they're likely outside the scope of this format.

`1483246800 "We lost power in the LGA colo, battery backup failed."`

3) Strings as time series. A lot of the time we inform users to avoid high-cardinality in their tags but they want to be able to track things like the app version, etc. If these are stored in labels, it's a new time series. But if you keep that in the value, it's much more obvious that "oh the version changed". And you can still perform a some time-series operations on strings, e.g. count, distinct, group-by, filtering, etc. Of course others don't make sense, but it is a time series with a fixed identifier unlike an unstructured event (ala a log entry).
Maybe @pauldix could comment on this use case in Influx.

```
myapp.version 1483246800 "0.0.1" host=web01, dc=phx
myapp.version 1483250400 "0.0.2" host=web01, dc=phx
myapp.version 1483254000 "0.0.2" host=web01, dc=phx
```

**Comment by brian-brazil** [comment]
Cases 1 and 2 are event logging.

Case 3 is covered by the annotations pattern.
