### ISSUE TITLE
Support for geo-time series metrics?

### ISSUE THREAD

**Issue by manolama** [OpenObservability/OpenMetrics#50]
Paul briefly touched on it but there is a huge amount of interest in geo-time series info, i.e. numeric values with coordinates. We should be forward thinking and account for this. Probably a first level data type ala histograms would be fine.

**Comment by brian-brazil** [comment]
This is fundamentally two gauges, so a composite type is plausible.

**Comment by StevenLeRoux** [comment]
Two cases : 
 - Geo is first class citizen alongside with Time
 - Geo is a reserved label 

The 1st implies that Time and Geo can be represented in the input/exposition format.
Warp10 accomplish that in a nice optional format : 

  1525826237000000// not.geo.ts{} "value"
  1525826237000000/4.183554:-1.323344/42 geo.ts{} "value"

Which represents : time/lat:lon/elevation
Geo can be omitted. Time is platform related (from ms to ns)

**Comment by brian-brazil** [comment]
The consensus is that we don't want lots of special cases, so this can be done by users using existing gauges.

**Comment by StevenLeRoux** [comment]
I don't get how you map the four dimensions (time, lat, lon, elevation) to a single gauge without using some reserved labels for this.

I don't like this idea of special labels because it's a source of conflict between user related data model and functions that rely on these labels.

Instead I find something like this more interesting  : 

- timestamp (current encoding for most of the time series platforms)
- timestamp// (geo format but omitted)
- timestamp/lat:lon/elev

This way, time series platforms with geo support can leverage the 4 dimensions, without having to pervert the user defined data model.

Also, it allows for custom geo index that would get data from geo coordinates instead of time.
