### ISSUE TITLE
All histogram/summary stats need to be based on raw counters

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#64]
There are two ways of calculating averages and standard deviations proposed in the protos.

One is the Prometheus way, which is to have _sum, _count and (new for us) _sum_of_squares. These are counters, and it is possible to use these in PromQL as `rate(_sum_of_squares) / rate(_count)` and `sqrt((rate(_sum_of_squares) - (rate(_sum) ^ 2 / rate(_count)) / rate(_count))`

The other is to have _mean and _sum_of_squares_deviation. These are gauges, and are not possible to use in PromQL or Prometheus generally. Our best practices actually recommend [dropping them on the floor](https://prometheus.io/docs/instrumenting/writing_exporters/#drop-less-useful-statistics).

The Prometheus model is that you should be able to calculate a statistic over any time range, and a mean since the application started does not allow for this. Nor can it be aggregated. Generally we need raw data as counters, without any computation in client libraries as we'll handle that and any aggregation over in Prometheus. And thus we need  _sum, _count and _sum_of_squares.

_mean additionally has a precision issue. If you consider a nanosecond resolution integer latency metric for which latency is typically around a second, it'll only take a day at 10k qps before values can no longer affect the mean and thus losing all precision. By contrast a float64 value in the same situation but using _sum takes over 25 thousand years to lose all precision, and would maintain 4 digits of precision for at least a year.

[_sum_of_squares_deviation](http://www.stat.wisc.edu/~larget/math496/mean-var.html) has a similar issue.

For operational monitoring of latency and the like, I think 3-4 digits of precision is plenty. Beyond that noise will dominate, so more precision is misleading more than anything else.

**Comment by sumeer** [comment]
Lets separate the gauge/counter discussion from the discussion on the data model of the histogram/distribution. I'd like to focus on the data model first since with first-class composite types one shouldn't have to worry about the data-type of each scalar in a composite type.

Fleshing out your example of a 10K qps server wth nanosecond units latency with each sample with value ~1s.
- The mean is ~2^30, so we are getting approx 1/2^22 of precision. So to get to no change in the mean when adding a new sample x_k we need (x_k - m_(k-1)) / k < 1/2^22. So the effect on the mean depends on the value of x_k - m_(k-1). At 1ns it is 7min (2^22/10000 s) before k becomes large enough, at 1us it is 5 days before k becomes large enough.
     If we keep the sum instead of the mean, after 7min the sum is ~2^52 so our precision is reduced to 1ns. After 5 days the precision is reduced to 1us. 
     So I think the situation is the same with mean or sum. Does the above agree with your calculations?
  - For the sum of squares versus sum of squares deviation can you share your calculations? With sum of squares, in the above example, each square is ~2^60, so our precision starts of with 2^8 ns^2. This large number situation was what the provisional means method was trying to tackle.

**Comment by brian-brazil** [comment]
> Lets separate the gauge/counter discussion from the discussion on the data model of the histogram/distribution.

These are fundamentally tied together for us. Prometheus needs counters for these in order for them to be of use.

> Does the above agree with your calculations?

By a quick back of the envelope, your numbers appear to be largely consistent with mine.

> For the sum of squares versus sum of squares deviation can you share your calculations?

Due to the squaring, for a sum of squares a float64 will have 26.5 bits of precision and all precision would be lost within 2 hours. 10000 * 3600 * 2 > 2^26
A uint64 with nanosecond resolution  sum of squares and all precision would be lost instantly due to overflow in under a second. (10^9) ^ 2  * 10000 >  2^64

For the sum of squares deviation, it depends on the deviation. Let's say it's 10% on average (probably small, but anyway...). For the float64 it'll have 26.5 bits of precision. All precision will be lost within about 2 hours. 10000 * 3600 * 2 > 2^26

With a uint64 with nanosecond resolution for the sum of squares deviation, it'll overflow in under a second. (10^8)^2 * 10000  > 2^64

So looking at this, I'm not sure calculating the standard deviation is viable at all within the data types we have available. The best option only keeps precision for 100M queries, which is not many at all.

**Comment by sumeer** [comment]
Regarding sum of squares, iiuc, your "all precision lost" transition is when precision is > 1. So with 1/2^26.5 precision initially due to squaring, and the example samples of ~2^30 (1s latency represented as nanos) the first sample itself sees precision > 1.

While with sum of square deviation and the example of ~12% deviation from mean, each sample is approximately (sample - mean), so is ~2^27 (2^30 / 100 / 12 ). The rate of precision loss is approximately 1/8th of the sum of squares. This is what http://www.stat.wisc.edu/~larget/math496/mean-var.html is focusing on wrt small deviation values and large sample values. 

Of course, in all cases we will eventually need to reset the cumulative value.

**Comment by brian-brazil** [comment]
> The rate of precision loss is approximately 1/8th of the sum of squares. 

I think you need to take the square root of that so it's nearer 1/3, presuming a low ~10% deviation. Not that it makes much difference given the magnitudes involved.

> Of course, in all cases we will eventually need to reset the cumulative value.

My argument is that this is required so frequently that this is unworkable for float64 as it'd require a reset every few seconds to get 3 digits of precision, and completely unworkable for uint64.

I don't think that something that requires resets even daily is practical.

**Comment by sumeer** [comment]
- I'm assuming you are not suggesting we drop support for computing standard deviation from prometheus and monarch. Am I correct?

- I computed incorrectly. The sum of squares deviation loses precision at 1/64th the rate of sum of squares in this example. Also, this example is an outlier -- most services are lower qps and can derive benefit from standard deviation. And resets are very practical in a push model since the client has control and can avoid losing data.

- Monarch will continue to store sum of square deviation given the higher precision, and prometheus will continue to support sum of squares (iiuc). I have the following suggestion to unblock this and the flattening issue (counters/gauges and bucketing specifications).
   - the data model has a composite type for histogram with bucketing specification, mean/sum (I don't care which since they have equal precision), count, sum-of-squares-deviation (higher precision than sum-of-squares)
   - the wire protocol would allows for wire format negotiation. The minimum requirement for a client library would be the text format, but we will make a strong effort to support a structured format in the blessed libraries.
  - the text format is flat, omits the bucketing specification, sends sum, count and sum-of-squares (the library can convert from sum-of-squares-deviation to sum-of-squares), so everything can be a counter.
  - the structured formats (e.g. protos) mirrors the data model.
 One critique of this approach is that the client data model does not match what is visible to queries. I think this is to be expected given the diversity of backends -- for instance monarch/stackdriver will not natively support the summary type for storage or querying. Users need to understand the backend they are using anyway due to the diversity of the typing (stronger typing like monarch/stackdriver with descriptors or weaker typing with prometheus), and the diversity of the query languages.

**Comment by brian-brazil** [comment]
> I'm assuming you are not suggesting we drop support for computing standard deviation from prometheus and monarch. Am I correct?

I am suggesting this. Prometheus has no such support currently, and the above math indicates it's impractical to support given precision.

> Also, this example is an outlier -- most services are lower qps and can derive benefit from standard deviation. 

This standard also needs to cover things like 100G network ports, which can blow through 100M packets in a few seconds.

I believe that anything we add to the standard needs to work for both small and large systems. 100M queries is a small number. Even a system doing only a moderate 100qps will hit it in about 10 days.

> And resets are very practical in a push model since the client has control and can avoid losing data.

The standard needs to support both push and pull, and irregular pushes could cause a DDoS. Such an approach is straying into event logging.

> the wire protocol would allows for wire format negotiation. The minimum requirement for a client library would be the text format, but we will make a strong effort to support a structured format in the blessed libraries.

I fail to see what structure has to do with the precision issue.

At the in person meeting I suggested a solution that'd allow for graceful extension of precision, and it was frowned upon. Only uint64 and float64 are to be supported as it stands, and there was a strong desire to avoid vendor-specific extensions.

> the text format is flat, omits the bucketing specification, sends sum, count and sum-of-squares (the library can convert from sum-of-squares-deviation to sum-of-squares), so everything can be a counter.

Any format should be sending the same numbers as the text format, just marshalled/compressed a bit differently.

Converting from  sum-of-squares-deviation to sum-of-squares will lose precision, and may make it not a counter if it can go backwards. We generally try to with Prometheus to encourage math to be done in the monitoring system rather than in the client. Additionally here I'd worry that implementors would tend to get this wrong, as this is a moderately subtle issue.

> One critique of this approach is that the client data model does not match what is visible to queries. I think this is to be expected given the diversity of backends

Yes, this is completely expected to me. We already have this today with Prometheus to some extent.

**Comment by RichiH** [comment]
@sumeer will discuss internally and get back to this issue.

**Comment by sumeer** [comment]
I think it is ok to leave out standard deviation from the spec

**Comment by brian-brazil** [comment]
Sounds like we have consensus. It is unfortunate that it doesn't work out mathematically, but we can add it later if/when float128 becomes a thing.

**Comment by vadimonus** [comment]
Returning to this discussion five years later.
Take a look at Postgresql,  https://github.com/postgres/postgres/blob/3e071b2cf584052b0799ebbc4d38ecfdb5bd701a/src/backend/utils/adt/float.c#L2986 , it uses youngs-cramer algorithm (https://www.jstor.org/stable/1267176) to minimize error when calculating stddev. I do not have access to full paper, thus looking to postgresql code, it uses internal counter to store residual-sum-of-sqares instead of sum-of-sqaures. Also take a look at https://www.google.ru/books/edition/Statistical_Computing_in_C++_and_R/q3nNBQAAQBAJ , pages 26-30. If i understanded correctly, such algorithm reduces error, as residual-sum-of-sqares does not grow as quickly as sum-of-sqares.

May be using  _residual_sum_of_sqares counter with float64 is solution for this case?

**Comment by brian-brazil** [comment]
Sum squares deviation was considered up above in https://github.com/OpenObservability/OpenMetrics/issues/64#issuecomment-338722816, and unfortunately it doesn't work out precision wise.

Looking at that Postgres code, what it's doing is incrementing by the mean deviation divided by the number of samples (ish). This looks to correspond to S7 in the paper. The algorithm you suggest might be a small bit more accurate, but we're still greatly limited by the bits in a float due to the squaring.

**Comment by vadimonus** [comment]
@brian-brazil , thanks for clarification
